### ISSUE TITLE
broken - jumping to file

### ISSUE THREAD

**Issue by Konfekt** [saccarosium/vim-netrw-salad#2]
With `vim --clean -u ~/.vimrc` and `~/.vimrc` reading

```vim
set nocompatible
filetype plugin indent on
syntax on
```

and Vim 9.1.369 on Ubuntu 20.04 and `autoload/netrw.vim` from `2024 Apr 03`, then `e ~/.vim/vimrc<cr>-` should position the cursor at the file `vimrc`. 
Instead, it is positioned at `\..`, the first line after the banner.

**Comment by Konfekt** [comment]
Maybe relevant: https://github.com/tpope/vim-vinegar/issues/136

**Comment by saccarosium** [comment]
Hey, sorry for the late responce. I was pretty busy.

I don't really get what you are reporting.

Do you mean:

If for example you are editing foo.vim, you press `-` and you are expecting that the cursor would be over the file you are editing. 

```
../ < But it is located here?
./
foo.vim < You want the cursor here
bar.txt
foobar.vim
```

**Comment by Konfekt** [comment]
Yes, exactly, the issue is as you describe.
